<?php
namespace app\pc\controller;
use think\Session;

class Details extends \think\Controller
{
    protected function _initialize()
    {
        $id =  input('id');        
        $this->assign('id',$id); //产品id  从url 传递过来
        parent::_initialize(); // TODO: Change the autogenerated stub
        //$this->assign('no_buy_btn',false);
    }

    public function index()
    {   
        $this->navInfo();
        return $this->fetch("index");
    }
    public function detail()
    {           
        //header基本信息
        $this->navInfo(); 
        //echo empty($user); 
        //isset(var)
        $user=Session::get('user_info');
        if(empty($user)){
            $user = 'null';
        }

        $this->assign('user',json_encode($user));

        $id = input('id');

        $goods_attr =db('goods_attr')->where("goods_id=$id")->select();

        $detail_info=db('detail_format')->where("id=$id")->find();
        
        foreach($goods_attr as $key => $value){
            $goods_color = db('color')->where("attr_id",$value['id'])->select();
            $goods_attr[$key]['goods_color'] = $goods_color;
        }
        $detail_info['goods_attr'] = $goods_attr;
        //$detail_info['goods_color'] = $goods_color;  

        //局域网图片添加  显示需拼接地址 __IMAGE__ (在config配置)在界面渲染时会替换。
        $detail_info['goods_image'] =  '__IMAGE__'.$detail_info['goods_image'];
        $this->assign('detail_info',json_encode($detail_info)); 
        /*print_r($detail_info);
        exit();*/
        $detail_list=array(
        'cmbProvince' => input('cmbProvince'),
        'cmbCity'=>input('cmbCity'),
        'cmbArea'=>input('cmbArea'),
       );
       //print_r($detail_list);
       $this->assign('detail_list',$detail_list);
       
       // print_r($detail_info);

       $data =$detail_info['goods_attr'];
       // print_r(['goods_color']);

       // exit();
        return $this->fetch();
    }
    public function atlasPic()
    {
        $this->navInfo(); 
        return $this->fetch();
    }
    public function specs()
    {
        $this->navInfo(); 
        return $this->fetch();
    }
    public function add()
    {
        $this->navInfo(); 
        return $this->fetch();
    }

    /*------立即购买保存商品 API----*/
    public function submitBuyAjax() 
    {
        
        $data = input('data');
        
        $buyList = json_decode($data,true);
        $cartModel = model('cart');
        $cartModel->save($buyList);
       // echo $cartModel->getlastsql();
        return json(array('active'=>1));
        
    }

    public function navInfo()
    {
        $userData=Session::get('user_info');
        // print_r($user);
        //echo $user['username'];
        if (Session::get('user_id')) {
            $user_id=Session::get('user_id');
            $this->assign('user_id',$user_id);
            //待支付数量
            $cartList= db('cart')->where("user_id=$user_id")->select();
            $this->assign('cartList',$cartList);
            $cartNum = 0;
            
            foreach ($cartList as $key => $value) {
                $cartNum += $value['num'];               
            }
            
            $this->assign('cartNum',$cartNum);
            // print_r($cartNum);
        }else {

        }
        $this->assign('userData',$userData);
        
    }
}